version: "3.7"

services:  
  flask:
    build: ./
    container_name: flask_react_test_api
    restart: always
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    container_name: flask_react_test_nginx
    restart: always
    ports:
      - "80:80"